root = "."
testdata_dir = ""
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/sonoff"
  cmd = "go build -o bin/sonoff"
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
